### PR TITLE
Add else statement in 'find_column_type()' to cover all other data types

### PR DESCRIPTION
**Pull request by dasjyao**
This is to fix issue #103. 

Changes include:
1. added else statement at the end to parse all other data types to varchar. 
2. Included logger.Info() for print out. 
3. added both unit test and integration test.

### CODE REVIEW

**Review by fdosani — COMMENTED** [review]
LGTM. thanks for the tweak here. I'm wondering if we should add something to the docs to call this? @jborchma thoughts?

**Review by jborchma — CHANGES_REQUESTED** [review]
So yeah, I think adding a sentence to the docstring explaining the logic use would be good. I think it would be good to list the types that are supported and explain that if the column is in a non-supported type it will be `varchar`.

**Comment by fdosani** [comment]
@dasjyao Would you be ok to add some info to the docs on this?

**Comment by dasjyao** [comment]
> @dasjyao Would you be ok to add some info to the docs on this?

Yes of course! I was planning to do this during weekend.

**Comment by dasjyao** [comment]
@fdosani @jborchma have added some lines in find_column_type() docstring. Please let me know your thoughts.

**Review by jborchma — APPROVED** [review]
LGTM!

**Review by fdosani — APPROVED** [review]
LGTM

**Pull request merged**
