### PR TITLE
CLA and setup cleanup

### PR DESCRIPTION
**Pull request by fdosani**
- CLA verbiage was outdated
- Adding in `isort` to pre-commit
- cleaning up `setup.py`

### CODE REVIEW

**Comment by jborchma** [comment]
Do you want to use this new `dev` install in the github actions pipeline? You are currently using the dev requierements.txt.

**Review by jborchma — COMMENTED** [review]
Just the question below

**Comment by fdosani** [comment]
> Do you want to use this new `dev` install in the github actions pipeline? You are currently using the dev requierements.txt.

ahh right, nice catch. All over the place with this. Will tweak that, one sec.

**Review by jborchma — APPROVED** [review]
lgtm

**Pull request merged**
